name: Tests

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  ci:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 16, 18]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup playground
        run: yarn dev:prepare

      - name: Lint
        run: yarn lint

      - name: Check types
        run: yarn types

      - name: Run tests
        run: yarn test

      - name: Upload coverage to Codecov
        if: github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
